@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.maidbeacon.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;